import crypto from 'crypto';
import fs from 'fs/promises';
import path from 'path';
import { Pool } from 'pg';

export type UsuarioPerfil = {
  id: string;
  email: string;
  nome_completo: string;
  organizacao?: string | null;
  avatar_url?: string | null;
  created_at?: string;
  updated_at?: string;
};

let pool: Pool | null = null;

const getPool = () => {
  if (!pool) {
    const databaseUrl = process.env.DATABASE_URL || '';
    pool = new Pool(
      databaseUrl
        ? { connectionString: databaseUrl }
        : {
            host: process.env.PGHOST || '127.0.0.1',
            port: Number(process.env.PGPORT || 5432),
            database: process.env.PGDATABASE || 'rcmolina',
            user: process.env.PGUSER || 'rcmolina',
            password: process.env.PGPASSWORD || '',
          },
    );
  }

  return pool;
};

let initPromise: Promise<void> | null = null;

const schemaSql = `
create schema if not exists "RCMOLINASEGUROS";
create extension if not exists pgcrypto;

create table if not exists "RCMOLINASEGUROS"."USUARIOS" (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  nome_completo text not null,
  organizacao text,
  avatar_url text,
  senha_hash text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists "RCMOLINASEGUROS"."AUDITORIA" (
  id bigint generated by default as identity primary key,
  acao text not null,
  detalhes jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists "RCMOLINASEGUROS"."CODIGOS_LOGIN" (
  id uuid primary key default gen_random_uuid(),
  usuario_id uuid not null references "RCMOLINASEGUROS"."USUARIOS"(id) on delete cascade,
  email text not null,
  codigo_hash text not null,
  attempts integer not null default 0,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists usuarios_email_idx on "RCMOLINASEGUROS"."USUARIOS" (email);
create index if not exists usuarios_nome_idx on "RCMOLINASEGUROS"."USUARIOS" (nome_completo);
create index if not exists codigos_login_email_idx on "RCMOLINASEGUROS"."CODIGOS_LOGIN" (email, created_at desc);

create or replace function "RCMOLINASEGUROS".touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists trg_usuarios_touch_updated_at on "RCMOLINASEGUROS"."USUARIOS";
create trigger trg_usuarios_touch_updated_at
before update on "RCMOLINASEGUROS"."USUARIOS"
for each row
execute function "RCMOLINASEGUROS".touch_updated_at();
create table if not exists "RCMOLINASEGUROS"."CLIENTES" (
  id_cliente uuid primary key default gen_random_uuid(),
  nome_completo varchar(255) not null,
  cpf varchar(14),
  rg varchar(20),
  cnpj varchar(18),
  data_nascimento date,
  status_cliente varchar(20) default 'ATIVO',
  codigo varchar(50) default '000000',
  data_cadastro date default current_date,
  data_atualizacao timestamptz not null default timezone('utc', now()),
  cep varchar(9),
  logradouro varchar(255),
  numero varchar(20),
  complemento varchar(100),
  ponto_referencia varchar(255),
  bairro varchar(100),
  cidade varchar(100),
  uf varchar(2),
  observacoes_extras text,
  marcacoes varchar(255),
  como_conheceu varchar(100) default '0 - Não informado',
  permite_agendar_online boolean default true,
  documentacao_anotacoes text
);

create table if not exists "RCMOLINASEGUROS"."CLIENTES_CONTATOS" (
  id_contato uuid primary key default gen_random_uuid(),
  id_cliente uuid not null references "RCMOLINASEGUROS"."CLIENTES"(id_cliente) on delete cascade,
  tipo varchar(50) not null,
  valor varchar(100) not null,
  complemento varchar(100),
  observacoes varchar(255),
  preferencial boolean default false,
  criado_em timestamptz default timezone('utc', now())
);

create table if not exists "RCMOLINASEGUROS"."CLIENTES_ANEXOS" (
  id_anexo uuid primary key default gen_random_uuid(),
  id_cliente uuid not null references "RCMOLINASEGUROS"."CLIENTES"(id_cliente) on delete cascade,
  nome_arquivo varchar(255) not null,
  caminho_arquivo varchar(500) not null,
  tamanho_bytes integer,
  tipo_mime varchar(100),
  criado_em timestamptz default timezone('utc', now())
);

drop trigger if exists trg_clientes_touch_updated_at on "RCMOLINASEGUROS"."CLIENTES";
create trigger trg_clientes_touch_updated_at
before update on "RCMOLINASEGUROS"."CLIENTES"
for each row
execute function "RCMOLINASEGUROS".touch_updated_at();

`;

const rowToPerfil = (row: any): UsuarioPerfil => ({
  id: row.id,
  email: row.email,
  nome_completo: row.nome_completo,
  organizacao: row.organizacao,
  avatar_url: row.avatar_url,
  created_at: row.created_at?.toISOString?.() || row.created_at,
  updated_at: row.updated_at?.toISOString?.() || row.updated_at,
});

export const initLocalDatabase = async () => {
  if (!initPromise) {
    initPromise = (async () => {
      await getPool().query(schemaSql);
      await seedAdminUser();
    })();
  }

  return initPromise;
};

export const localDatabaseStatus = async () => {
  await initLocalDatabase();
  const result = await getPool().query(`
    select
      current_database() as database,
      current_user as "user",
      (
        select count(*)
        from information_schema.tables
        where table_schema = 'RCMOLINASEGUROS'
      )::int as tables
  `);

  return result.rows[0];
};

const seedAdminUser = async () => {
  const adminEmail = (process.env.ADMIN_EMAIL || 'admin@rcmolina.com.br').trim().toLowerCase();
  const adminPassword = process.env.ADMIN_INITIAL_PASSWORD || '';

  if (!adminPassword) return;

  const existing = await getPool().query('select 1 from "RCMOLINASEGUROS"."USUARIOS" where lower(email) = $1 limit 1', [
    adminEmail,
  ]);

  if (existing.rowCount) {
    await getPool().query(
      `update "RCMOLINASEGUROS"."USUARIOS"
       set senha_hash = crypt($2, gen_salt('bf')),
           nome_completo = coalesce(nullif(trim(nome_completo), ''), $3),
           organizacao = coalesce(nullif(trim(organizacao), ''), $4)
       where lower(email) = $1`,
      [adminEmail, adminPassword, 'ADMINISTRADOR RC MOLINA', 'RC MOLINA'],
    );
    return;
  }

  await getPool().query(
    `insert into "RCMOLINASEGUROS"."USUARIOS" (email, senha_hash, nome_completo, organizacao)
     values ($1, crypt($2, gen_salt('bf')), $3, $4)`,
    [adminEmail, adminPassword, 'ADMINISTRADOR RC MOLINA', 'RC MOLINA'],
  );
};

export const registrarAuditoria = async (acao: string, detalhes: Record<string, unknown> = {}) => {
  await initLocalDatabase();
  await getPool().query('insert into "RCMOLINASEGUROS"."AUDITORIA" (acao, detalhes) values ($1, $2)', [acao, detalhes]);
};

export const usuariosEmailExiste = async (email: string) => {
  await initLocalDatabase();
  const result = await getPool().query(
    'select exists(select 1 from "RCMOLINASEGUROS"."USUARIOS" where lower(email) = lower(trim($1))) as exists',
    [email],
  );
  return Boolean(result.rows[0]?.exists);
};

export const usuariosPerfil = async (id: string) => {
  await initLocalDatabase();
  const result = await getPool().query('select * from "RCMOLINASEGUROS"."USUARIOS" where id = $1 limit 1', [id]);
  return result.rows[0] ? rowToPerfil(result.rows[0]) : null;
};

export const usuariosLogin = async (email: string, senha: string) => {
  await initLocalDatabase();
  const result = await getPool().query(
    `select *
     from "RCMOLINASEGUROS"."USUARIOS"
     where lower(email) = lower(trim($1))
       and senha_hash = crypt($2, senha_hash)
     limit 1`,
    [email, senha],
  );
  return result.rows[0] ? rowToPerfil(result.rows[0]) : null;
};

export const usuariosCadastrar = async ({
  email,
  senha,
  nomeCompleto,
  organizacao,
  avatarUrl,
}: {
  email: string;
  senha: string;
  nomeCompleto: string;
  organizacao?: string | null;
  avatarUrl?: string | null;
}) => {
  await initLocalDatabase();
  const result = await getPool().query(
    `insert into "RCMOLINASEGUROS"."USUARIOS" (email, senha_hash, nome_completo, organizacao, avatar_url)
     values (lower(trim($1)), crypt($2, gen_salt('bf')), upper(trim($3)), nullif(trim($4), ''), nullif(trim($5), ''))
     returning *`,
    [email, senha, nomeCompleto, organizacao || '', avatarUrl || ''],
  );
  await registrarAuditoria('USUARIO_CADASTRADO', { email });
  return rowToPerfil(result.rows[0]);
};

export const usuariosGerarCodigoLogin = async (email: string) => {
  await initLocalDatabase();
  const normalizedEmail = email.trim().toLowerCase();
  const user = await getPool().query(
    'select id from "RCMOLINASEGUROS"."USUARIOS" where lower(email) = $1 limit 1',
    [normalizedEmail],
  );

  if (!user.rows[0]) return null;

  const recent = await getPool().query(
    `select 1 from "RCMOLINASEGUROS"."CODIGOS_LOGIN"
     where email = $1 and created_at >= (timezone('utc', now()) - interval '60 seconds')
     limit 1`,
    [normalizedEmail],
  );

  if (recent.rowCount) {
    const error = new Error('RATE_LIMIT');
    error.name = 'RATE_LIMIT';
    throw error;
  }

  const codigo = crypto.randomInt(0, 1000000).toString().padStart(6, '0');
  const result = await getPool().query(
    `insert into "RCMOLINASEGUROS"."CODIGOS_LOGIN" (usuario_id, email, codigo_hash, expires_at)
     values ($1, $2, crypt($3, gen_salt('bf')), timezone('utc', now()) + interval '10 minutes')
     returning expires_at`,
    [user.rows[0].id, normalizedEmail, codigo],
  );

  return {
    codigo,
    expira_em: result.rows[0]?.expires_at,
  };
};

export const usuariosVerificarCodigoLogin = async (email: string, codigo: string) => {
  await initLocalDatabase();
  const normalizedEmail = email.trim().toLowerCase();
  const codeResult = await getPool().query(
    `select *
     from "RCMOLINASEGUROS"."CODIGOS_LOGIN"
     where email = $1
       and used_at is null
       and expires_at > timezone('utc', now())
       and attempts < 5
     order by created_at desc
     limit 1`,
    [normalizedEmail],
  );
  const row = codeResult.rows[0];

  if (!row) return null;

  const valid = await getPool().query('select $1 = crypt($2, $1) as valid', [row.codigo_hash, codigo]);

  if (!valid.rows[0]?.valid) {
    await getPool().query('update "RCMOLINASEGUROS"."CODIGOS_LOGIN" set attempts = attempts + 1 where id = $1', [
      row.id,
    ]);
    return null;
  }

  await getPool().query(
    `update "RCMOLINASEGUROS"."CODIGOS_LOGIN"
     set used_at = timezone('utc', now()), attempts = attempts + 1
     where id = $1`,
    [row.id],
  );

  return usuariosPerfil(row.usuario_id);
};

export const usuariosResetarSenhaComCodigo = async (email: string, codigo: string, novaSenha: string) => {
  await initLocalDatabase();
  const normalizedEmail = email.trim().toLowerCase();
  const codeResult = await getPool().query(
    `select *
     from "RCMOLINASEGUROS"."CODIGOS_LOGIN"
     where email = $1 and used_at is null
     order by created_at desc
     limit 1`,
    [normalizedEmail],
  );
  const row = codeResult.rows[0];

  if (!row) return { status: 'INVALID', message: 'Codigo nao encontrado.', remaining: 0 };
  if (new Date(row.expires_at).getTime() <= Date.now()) return { status: 'EXPIRED', message: 'Codigo expirado.' };
  if (row.attempts >= 5) return { status: 'BLOCKED', message: 'Codigo bloqueado.' };

  const valid = await getPool().query('select $1 = crypt($2, $1) as valid', [row.codigo_hash, codigo]);

  if (!valid.rows[0]?.valid) {
    const attempts = await getPool().query(
      `update "RCMOLINASEGUROS"."CODIGOS_LOGIN"
       set attempts = attempts + 1
       where id = $1
       returning attempts`,
      [row.id],
    );
    const remaining = Math.max(0, 5 - Number(attempts.rows[0]?.attempts || 5));
    return { status: 'INVALID', message: 'Codigo incorreto.', remaining };
  }

  await getPool().query(
    `update "RCMOLINASEGUROS"."USUARIOS"
     set senha_hash = crypt($1, gen_salt('bf')), updated_at = timezone('utc', now())
     where id = $2`,
    [novaSenha, row.usuario_id],
  );
  await getPool().query(
    `update "RCMOLINASEGUROS"."CODIGOS_LOGIN"
     set used_at = timezone('utc', now()), attempts = attempts + 1
     where id = $1`,
    [row.id],
  );
  await registrarAuditoria('RESET_SENHA', { email: normalizedEmail });

  return { status: 'SUCCESS', message: 'Senha atualizada com sucesso.' };
};

const authSecret = () => process.env.AUTH_SECRET || process.env.ADMIN_INITIAL_PASSWORD || 'rc-molina-dev-secret';

export const createAdminToken = (email: string) => {
  const payload = Buffer.from(
    JSON.stringify({
      email: email.trim().toLowerCase(),
      exp: Date.now() + 1000 * 60 * 60 * 8,
    }),
  ).toString('base64url');
  const signature = crypto.createHmac('sha256', authSecret()).update(payload).digest('base64url');
  return `${payload}.${signature}`;
};

export const verifyAdminToken = (token: string | undefined) => {
  if (!token) return false;
  const [payload, signature] = token.replace(/^Bearer\s+/i, '').split('.');
  if (!payload || !signature) return false;

  const expected = crypto.createHmac('sha256', authSecret()).update(payload).digest('base64url');
  if (!crypto.timingSafeEqual(Buffer.from(signature), Buffer.from(expected))) return false;

  const decoded = JSON.parse(Buffer.from(payload, 'base64url').toString('utf8')) as { email?: string; exp?: number };
  return decoded.email === (process.env.ADMIN_EMAIL || 'admin@rcmolina.com.br').toLowerCase() && Number(decoded.exp) > Date.now();
};

export const adminListUsers = async () => {
  await initLocalDatabase();
  const result = await getPool().query('select * from "RCMOLINASEGUROS"."USUARIOS" order by nome_completo');
  return result.rows.map(rowToPerfil);
};

export const adminUpdateUser = async ({
  id,
  nome,
  email,
  organizacao,
  avatarUrl,
}: {
  id: string;
  nome: string;
  email: string;
  organizacao?: string | null;
  avatarUrl?: string | null;
}) => {
  await initLocalDatabase();
  await getPool().query(
    `update "RCMOLINASEGUROS"."USUARIOS"
     set nome_completo = upper(trim($1)),
         email = lower(trim($2)),
         organizacao = nullif(trim($3), ''),
         avatar_url = nullif(trim($4), '')
     where id = $5`,
    [nome, email, organizacao || '', avatarUrl || '', id],
  );
  await registrarAuditoria('ADMIN_UPDATE_USER', { id, email });
};

export const adminDeleteUser = async (id: string) => {
  await initLocalDatabase();
  await getPool().query('delete from "RCMOLINASEGUROS"."USUARIOS" where id = $1', [id]);
  await registrarAuditoria('ADMIN_DELETE_USER', { id });
};

const avatarExtensionByMime: Record<string, string> = {
  'image/jpeg': 'jpg',
  'image/png': 'png',
  'image/webp': 'webp',
  'image/gif': 'gif',
  'image/bmp': 'bmp',
  'image/svg+xml': 'svg',
};

export const saveAvatarDataUrl = async (dataUrl?: string | null, originalName = 'avatar') => {
  if (!dataUrl) return null;

  const match = dataUrl.match(/^data:(image\/[a-zA-Z0-9.+-]+);base64,(.+)$/);
  if (!match) return null;

  const [, mime, base64] = match;
  const extension =
    avatarExtensionByMime[mime] || path.extname(originalName).replace(/^\./, '').toLowerCase() || 'png';
  const buffer = Buffer.from(base64, 'base64');

  if (buffer.length > 5 * 1024 * 1024) {
    throw new Error('A imagem do avatar deve ter no maximo 5 MB.');
  }

  const uploadRoot = process.env.UPLOAD_DIR || path.join(process.cwd(), 'uploads');
  const avatarDir = path.join(uploadRoot, 'avatars');
  await fs.mkdir(avatarDir, { recursive: true });

  const filename = `${crypto.randomUUID()}.${extension}`;
  const finalPath = path.join(avatarDir, filename);
  await fs.writeFile(finalPath, buffer);

  return `/uploads/avatars/${filename}`;
};
