create schema if not exists "RCMOLINASEGUROS";

create extension if not exists pgcrypto with schema extensions;

do $$
begin
  if exists (
    select 1
    from information_schema.tables
    where table_schema = 'public'
      and table_name = 'RCMOLINASEGUROS.USUARIOS'
  ) and not exists (
    select 1
    from information_schema.tables
    where table_schema = 'RCMOLINASEGUROS'
      and table_name = 'USUARIOS'
  ) then
    execute 'alter table public."RCMOLINASEGUROS.USUARIOS" rename to "USUARIOS"';
    execute 'alter table public."USUARIOS" set schema "RCMOLINASEGUROS"';
  elsif exists (
    select 1
    from information_schema.tables
    where table_schema = 'public'
      and table_name = 'USUARIOS'
  ) and not exists (
    select 1
    from information_schema.tables
    where table_schema = 'RCMOLINASEGUROS'
      and table_name = 'USUARIOS'
  ) then
    execute 'alter table public."USUARIOS" set schema "RCMOLINASEGUROS"';
  end if;

  if exists (
    select 1
    from information_schema.tables
    where table_schema = 'public'
      and table_name = 'RCMOLINASEGUROS.AUDITORIA'
  ) and not exists (
    select 1
    from information_schema.tables
    where table_schema = 'RCMOLINASEGUROS'
      and table_name = 'AUDITORIA'
  ) then
    execute 'alter table public."RCMOLINASEGUROS.AUDITORIA" rename to "AUDITORIA"';
    execute 'alter table public."AUDITORIA" set schema "RCMOLINASEGUROS"';
  elsif exists (
    select 1
    from information_schema.tables
    where table_schema = 'public'
      and table_name = 'AUDITORIA'
  ) and not exists (
    select 1
    from information_schema.tables
    where table_schema = 'RCMOLINASEGUROS'
      and table_name = 'AUDITORIA'
  ) then
    execute 'alter table public."AUDITORIA" set schema "RCMOLINASEGUROS"';
  end if;

  if exists (
    select 1
    from information_schema.tables
    where table_schema = 'public'
      and table_name = 'RCMOLINASEGUROS.CODIGOS_LOGIN'
  ) and not exists (
    select 1
    from information_schema.tables
    where table_schema = 'RCMOLINASEGUROS'
      and table_name = 'CODIGOS_LOGIN'
  ) then
    execute 'alter table public."RCMOLINASEGUROS.CODIGOS_LOGIN" rename to "CODIGOS_LOGIN"';
    execute 'alter table public."CODIGOS_LOGIN" set schema "RCMOLINASEGUROS"';
  elsif exists (
    select 1
    from information_schema.tables
    where table_schema = 'public'
      and table_name = 'CODIGOS_LOGIN'
  ) and not exists (
    select 1
    from information_schema.tables
    where table_schema = 'RCMOLINASEGUROS'
      and table_name = 'CODIGOS_LOGIN'
  ) then
    execute 'alter table public."CODIGOS_LOGIN" set schema "RCMOLINASEGUROS"';
  end if;
end $$;

create table if not exists "RCMOLINASEGUROS"."USUARIOS" (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  nome_completo text not null,
  organizacao text,
  avatar_url text,
  senha_hash text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists "RCMOLINASEGUROS"."AUDITORIA" (
  id bigint generated by default as identity primary key,
  acao text not null,
  detalhes jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists "RCMOLINASEGUROS"."CODIGOS_LOGIN" (
  id uuid primary key default gen_random_uuid(),
  usuario_id uuid not null references "RCMOLINASEGUROS"."USUARIOS"(id) on delete cascade,
  email text not null,
  codigo_hash text not null,
  attempts integer not null default 0,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default timezone('utc', now())
);

alter table "RCMOLINASEGUROS"."USUARIOS"
  add column if not exists created_at timestamptz not null default timezone('utc', now()),
  add column if not exists updated_at timestamptz not null default timezone('utc', now()),
  add column if not exists senha_hash text;

alter table "RCMOLINASEGUROS"."AUDITORIA"
  add column if not exists detalhes jsonb not null default '{}'::jsonb,
  add column if not exists created_at timestamptz not null default timezone('utc', now());

alter table "RCMOLINASEGUROS"."CODIGOS_LOGIN"
  add column if not exists attempts integer not null default 0,
  add column if not exists created_at timestamptz not null default timezone('utc', now());

create index if not exists usuarios_email_idx on "RCMOLINASEGUROS"."USUARIOS" (email);
create index if not exists usuarios_nome_idx on "RCMOLINASEGUROS"."USUARIOS" (nome_completo);
create index if not exists codigos_login_email_idx on "RCMOLINASEGUROS"."CODIGOS_LOGIN" (email, created_at desc);

create or replace function "RCMOLINASEGUROS".touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists trg_usuarios_touch_updated_at on "RCMOLINASEGUROS"."USUARIOS";
create trigger trg_usuarios_touch_updated_at
before update on "RCMOLINASEGUROS"."USUARIOS"
for each row
execute function "RCMOLINASEGUROS".touch_updated_at();

drop function if exists public.registrar_auditoria(text, jsonb);
drop function if exists public.usuarios_email_existe(text);
drop function if exists public.usuarios_perfil(uuid);
drop function if exists public.usuarios_perfil_por_email(text);
drop function if exists public.usuarios_cadastrar(text, text, text, text, text);
drop function if exists public.usuarios_login(text, text);
drop function if exists public.usuarios_atualizar_senha(text, text);
drop function if exists public.usuarios_gerar_codigo_login(text);
drop function if exists public.usuarios_verificar_codigo_login(text, text);
drop function if exists public.usuarios_resetar_senha_com_codigo(text, text, text);
drop function if exists public.admin_list_users();
drop function if exists public.admin_update_user(uuid, text, text, text, text);
drop function if exists public.admin_delete_user(uuid);

create or replace function public.registrar_auditoria(
  p_acao text,
  p_detalhes jsonb default '{}'::jsonb
) returns void
language plpgsql
security definer
set search_path = public, "RCMOLINASEGUROS", extensions
as $$
begin
  insert into "RCMOLINASEGUROS"."AUDITORIA" (acao, detalhes)
  values (p_acao, coalesce(p_detalhes, '{}'::jsonb));
end;
$$;

create or replace function public.usuarios_email_existe(p_email text)
returns boolean
language sql
security definer
set search_path = public, "RCMOLINASEGUROS", extensions
as $$
  select exists(
    select 1
    from "RCMOLINASEGUROS"."USUARIOS"
    where lower(email) = lower(trim(p_email))
  );
$$;

create or replace function public.usuarios_perfil(p_id uuid)
returns setof "RCMOLINASEGUROS"."USUARIOS"
language sql
security definer
set search_path = public, "RCMOLINASEGUROS", extensions
as $$
  select *
  from "RCMOLINASEGUROS"."USUARIOS"
  where id = p_id;
$$;

create or replace function public.usuarios_perfil_por_email(p_email text)
returns setof "RCMOLINASEGUROS"."USUARIOS"
language sql
security definer
set search_path = public, "RCMOLINASEGUROS", extensions
as $$
  select *
  from "RCMOLINASEGUROS"."USUARIOS"
  where lower(email) = lower(trim(p_email))
  order by created_at desc
  limit 1;
$$;

create or replace function public.usuarios_cadastrar(
  p_email text,
  p_senha text,
  p_nome_completo text,
  p_organizacao text default null,
  p_avatar_url text default null
) returns uuid
language plpgsql
security definer
set search_path = public, "RCMOLINASEGUROS", extensions
as $$
declare
  v_email text := lower(trim(p_email));
  v_user_id uuid;
begin
  if exists (
    select 1
    from "RCMOLINASEGUROS"."USUARIOS"
    where lower(email) = v_email
  ) then
    raise exception 'Este e-mail já está cadastrado.';
  end if;

  insert into "RCMOLINASEGUROS"."USUARIOS" (
    email,
    senha_hash,
    nome_completo,
    organizacao,
    avatar_url
  )
  values (
    v_email,
    crypt(p_senha, gen_salt('bf')),
    upper(trim(p_nome_completo)),
    nullif(trim(p_organizacao), ''),
    nullif(trim(p_avatar_url), '')
  )
  returning id into v_user_id;

  return v_user_id;
end;
$$;

create or replace function public.usuarios_login(
  p_email text,
  p_senha text
) returns setof "RCMOLINASEGUROS"."USUARIOS"
language sql
security definer
set search_path = public, "RCMOLINASEGUROS", extensions
as $$
  select *
  from "RCMOLINASEGUROS"."USUARIOS"
  where lower(email) = lower(trim(p_email))
    and senha_hash = crypt(p_senha, senha_hash)
  limit 1;
$$;

create or replace function public.usuarios_atualizar_senha(
  p_email text,
  p_nova_senha text
) returns void
language plpgsql
security definer
set search_path = public, "RCMOLINASEGUROS", extensions
as $$
begin
  update "RCMOLINASEGUROS"."USUARIOS"
  set senha_hash = crypt(p_nova_senha, gen_salt('bf')),
      updated_at = timezone('utc', now())
  where lower(email) = lower(trim(p_email));
end;
$$;

create or replace function public.usuarios_gerar_codigo_login(p_email text)
returns table(codigo text, expira_em timestamptz)
language plpgsql
security definer
set search_path = public, "RCMOLINASEGUROS", extensions
as $$
declare
  v_email text := lower(trim(p_email));
  v_user_id uuid;
  v_codigo text;
  v_now timestamptz := timezone('utc', now());
begin
  select id
  into v_user_id
  from "RCMOLINASEGUROS"."USUARIOS"
  where lower(email) = v_email
  limit 1;

  if v_user_id is null then
    return;
  end if;

  if exists (
    select 1
    from "RCMOLINASEGUROS"."CODIGOS_LOGIN"
    where email = v_email
      and created_at >= (v_now - interval '60 seconds')
  ) then
    raise exception 'RATE_LIMIT';
  end if;

  v_codigo := lpad(((random() * 999999)::int)::text, 6, '0');

  insert into "RCMOLINASEGUROS"."CODIGOS_LOGIN" (
    usuario_id,
    email,
    codigo_hash,
    expires_at
  )
  values (
    v_user_id,
    v_email,
    crypt(v_codigo, gen_salt('bf')),
    v_now + interval '10 minutes'
  );

  return query
  select v_codigo, v_now + interval '10 minutes';
end;
$$;

create or replace function public.usuarios_verificar_codigo_login(
  p_email text,
  p_codigo text
) returns setof "RCMOLINASEGUROS"."USUARIOS"
language plpgsql
security definer
set search_path = public, "RCMOLINASEGUROS", extensions
as $$
declare
  v_email text := lower(trim(p_email));
  v_codigo_row "RCMOLINASEGUROS"."CODIGOS_LOGIN"%rowtype;
begin
  select *
  into v_codigo_row
  from "RCMOLINASEGUROS"."CODIGOS_LOGIN"
  where email = v_email
    and used_at is null
    and expires_at > timezone('utc', now())
    and attempts < 5
  order by created_at desc
  limit 1;

  if not found then
    return;
  end if;

  if v_codigo_row.codigo_hash <> crypt(p_codigo, v_codigo_row.codigo_hash) then
    update "RCMOLINASEGUROS"."CODIGOS_LOGIN"
    set attempts = attempts + 1
    where id = v_codigo_row.id;
    return;
  end if;

  update "RCMOLINASEGUROS"."CODIGOS_LOGIN"
  set used_at = timezone('utc', now()),
      attempts = attempts + 1
  where id = v_codigo_row.id;

  return query
  select *
  from "RCMOLINASEGUROS"."USUARIOS"
  where id = v_codigo_row.usuario_id;
end;
$$;

create or replace function public.usuarios_resetar_senha_com_codigo(
  p_email text,
  p_codigo text,
  p_nova_senha text
) returns jsonb
language plpgsql
security definer
set search_path = public, "RCMOLINASEGUROS", extensions
as $$
declare
  v_email text := lower(trim(p_email));
  v_codigo_row "RCMOLINASEGUROS"."CODIGOS_LOGIN"%rowtype;
  v_remaining integer;
begin
  select *
  into v_codigo_row
  from "RCMOLINASEGUROS"."CODIGOS_LOGIN"
  where email = v_email
    and used_at is null
  order by created_at desc
  limit 1;

  if not found then
    return jsonb_build_object('status', 'INVALID', 'message', 'Codigo nao encontrado.', 'remaining', 0);
  end if;

  if v_codigo_row.expires_at <= timezone('utc', now()) then
    return jsonb_build_object('status', 'EXPIRED', 'message', 'Codigo expirado.');
  end if;

  if v_codigo_row.attempts >= 5 then
    return jsonb_build_object('status', 'BLOCKED', 'message', 'Codigo bloqueado.');
  end if;

  if v_codigo_row.codigo_hash <> crypt(p_codigo, v_codigo_row.codigo_hash) then
    update "RCMOLINASEGUROS"."CODIGOS_LOGIN"
    set attempts = attempts + 1
    where id = v_codigo_row.id
    returning greatest(0, 5 - attempts) into v_remaining;

    return jsonb_build_object(
      'status', 'INVALID',
      'message', 'Codigo incorreto.',
      'remaining', greatest(coalesce(v_remaining, 0), 0)
    );
  end if;

  update "RCMOLINASEGUROS"."USUARIOS"
  set senha_hash = crypt(p_nova_senha, gen_salt('bf')),
      updated_at = timezone('utc', now())
  where id = v_codigo_row.usuario_id;

  update "RCMOLINASEGUROS"."CODIGOS_LOGIN"
  set used_at = timezone('utc', now()),
      attempts = attempts + 1
  where id = v_codigo_row.id;

  return jsonb_build_object('status', 'SUCCESS', 'message', 'Senha atualizada com sucesso.');
end;
$$;

create or replace function public.admin_list_users()
returns setof "RCMOLINASEGUROS"."USUARIOS"
language plpgsql
security definer
set search_path = public, "RCMOLINASEGUROS", extensions
as $$
begin
  if auth.jwt() ->> 'email' != 'admin@rcmolina.com.br' then
    raise exception 'Acesso negado: você não tem permissão de administrador.';
  end if;

  return query
  select *
  from "RCMOLINASEGUROS"."USUARIOS"
  order by nome_completo;
end;
$$;

create or replace function public.admin_update_user(
  p_id uuid,
  p_nome text,
  p_email text,
  p_org text,
  p_avatar_url text
) returns void
language plpgsql
security definer
set search_path = public, "RCMOLINASEGUROS", extensions
as $$
begin
  if auth.jwt() ->> 'email' != 'admin@rcmolina.com.br' then
    raise exception 'Acesso negado: você não tem permissão para alterar usuários.';
  end if;

  update "RCMOLINASEGUROS"."USUARIOS"
  set nome_completo = upper(trim(p_nome)),
      email = lower(trim(p_email)),
      organizacao = nullif(trim(p_org), ''),
      avatar_url = nullif(trim(p_avatar_url), ''),
      updated_at = timezone('utc', now())
  where id = p_id;
end;
$$;

create or replace function public.admin_delete_user(p_id uuid)
returns void
language plpgsql
security definer
set search_path = public, "RCMOLINASEGUROS", extensions
as $$
begin
  if auth.jwt() ->> 'email' != 'admin@rcmolina.com.br' then
    raise exception 'Acesso negado: você não tem permissão para excluir usuários.';
  end if;

  delete from "RCMOLINASEGUROS"."USUARIOS"
  where id = p_id;
end;
$$;

grant usage on schema "RCMOLINASEGUROS" to anon, authenticated, service_role;
grant execute on function public.registrar_auditoria(text, jsonb) to anon, authenticated, service_role;
grant execute on function public.usuarios_email_existe(text) to anon, authenticated, service_role;
grant execute on function public.usuarios_perfil(uuid) to anon, authenticated, service_role;
grant execute on function public.usuarios_perfil_por_email(text) to anon, authenticated, service_role;
grant execute on function public.usuarios_cadastrar(text, text, text, text, text) to anon, authenticated, service_role;
grant execute on function public.usuarios_login(text, text) to anon, authenticated, service_role;
grant execute on function public.usuarios_atualizar_senha(text, text) to anon, authenticated, service_role;
grant execute on function public.usuarios_gerar_codigo_login(text) to anon, authenticated, service_role;
grant execute on function public.usuarios_verificar_codigo_login(text, text) to anon, authenticated, service_role;
grant execute on function public.usuarios_resetar_senha_com_codigo(text, text, text) to anon, authenticated, service_role;
grant execute on function public.admin_list_users() to authenticated, service_role;
grant execute on function public.admin_update_user(uuid, text, text, text, text) to authenticated, service_role;
grant execute on function public.admin_delete_user(uuid) to authenticated, service_role;
